name: First CI/CD Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "🚀 CI/CD is working! Let's gooo !"
